### ISSUE TITLE
ImportError: No module named 'path'

### ISSUE THREAD

**Issue by SeekPoint** [donglixp/coarse2fine#19]
mldl@ub1604:~/ub16_prj/coarse2fine$ bash run.sh atis 0
Traceback (most recent call last):
  File "preprocess.py", line 6, in <module>
    from path import Path
ImportError: No module named 'path'
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import table
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/__init__.py", line 2, in <module>
    import table.Models
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/Models.py", line 10, in <module>
    from table.Utils import aeq, sort_for_pack
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/Utils.py", line 2, in <module>
    from path import Path
ImportError: No module named 'path'
Traceback (most recent call last):
  File "evaluate.py", line 8, in <module>
    import table
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/__init__.py", line 2, in <module>
    import table.Models
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/Models.py", line 10, in <module>
    from table.Utils import aeq, sort_for_pack
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/Utils.py", line 2, in <module>
    from path import Path
ImportError: No module named 'path'
head: cannot open '/home/mldl/ub16_prj/coarse2fine/data_model/atis/dev_best.txt' for reading: No such file or directory
Traceback (most recent call last):
  File "evaluate.py", line 8, in <module>
    import table
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/__init__.py", line 2, in <module>
    import table.Models
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/Models.py", line 10, in <module>
    from table.Utils import aeq, sort_for_pack
  File "/home/mldl/ub16_prj/coarse2fine/logical/table/Utils.py", line 2, in <module>
    from path import Path
ImportError: No module named 'path'
mldl@ub1604:~/ub16_prj/coarse2fine$

**Comment by donglixp** [comment]
Hi @loveJasmine ,

Requirements

- Python 3.5
- [PyTorch 0.2.0.post3](https://pytorch.org/previous-versions/) (GPU)

Install Python dependency

```sh
pip install -r requirements.txt
```

Li

**Comment by SeekPoint** [comment]
am i missing some files?

mldl@ub1604:~/ub16_prj/coarse2fine$ bash run.sh atis 0
Preparing training ...
Building Training...
Building Valid...
Building Test...
Building Vocab...
Saving train/valid/fields
run.sh: line 23: 25247 Segmentation fault      (core dumped) CUDA_VISIBLE_DEVICES=$GPU_ID python3 train.py -root_dir "$WORK_DIR/data_model/" -dataset $DATANAME -rnn_size 250 -word_vec_size 200 -decoder_input_size 150 -layers 1 -start_checkpoint_at 60 -learning_rate 0.005 -start_decay_at 0 -epochs 100 -global_attention "dot" -attn_hidden 0 -lock_dropout -dropout 0.5 -dropout_i 0.5
head: cannot open '/home/mldl/ub16_prj/coarse2fine/data_model/atis/dev_best.txt' for reading: No such file or directory
mldl@ub1604:~/ub16_prj/coarse2fine$

**Comment by donglixp** [comment]
Please refer to #21 . Thanks
